# `U` is a predefined unit of measure that means 19.05mm, which is MX spacing
meta:
  engine: 4.1.0
units:
  mxX: u
  mxY: u
points:
  zones:
    matrix:
      columns:
        pinky0:
          key:
            column_net: P1 
        pinky1:
          key:
            column_net: P0
        ring:
          key:
            column_net: P2
            stagger: 0.66U
            bind: [0,0,23.82,0]
          rows.modifiers.skip: true
        middle:
          key:
            column_net: P3
            stagger: 0.25U
            bind: [0,0,20,0]
          rows.modifiers.skip: true
        index0:
          key:
            column_net: P4
            stagger: -0.25U
            bind: [0,0,22,0]
          rows.modifiers.skip: true
        index1:
          key:
            column_net: P5
            stagger: -0.15U
            bind: [0,0,22,0]
          rows.modifiers.skip: true
      rows:
        modifiers:
          row_net: P14
          padding: U
        bottom:
          row_net: P15
          padding: U
        home:
          row_net: P18
          padding: U
        top:
          row_net: P19
          padding: U
        numerics:
          row_net: P20
          padding: U
    thumb:
      anchor:
        ref: matrix_ring_bottom
        shift: [1U, -1.25U]
      columns:
        tucky:
          key:
            row_net: P16
            column_net: P1
        reachy:
          key:
            row_net: P16
            column_net: P0
            spread: U
            splay: -10
            origin: [-0.5U, -0.5U]
        extra-reachy:
          key:
            row_net: P16
            column_net: P2
            spread: U
            splay: -10
            origin: [-0.5U, -0.5U]
            bind: [0,0.71,0,0]
        extra-extra-reachy:
          key:
            row_net: P16
            column_net: P3
            spread: U
            splay: -10
            origin: [-0.5U, -0.5U]
            bind: [0,0,0,0.71]
  mirror:
    ref: "thumb_extra-extra-reachy"
    distance: 4U
outlines:
  _left_no_mcu:
    - where: [/^matrix_*/gm, /^thumb_*/gm]
      what: rectangle
      size: [cx + 3, cy + 3]
      bound: true
      fillet: .5
  _right_no_mcu:
    - where: /^mirror_*/gm
      what: rectangle
      size: [cx + 3, cy + 3]
      bound: true
      fillet: .5
  _keycap_outlines:
    - what: rectangle
      fillet: 2
      where: true
      size: [mxX, mxY]
  right:
    - what: outline
      name: _right_no_mcu
    - what: polygon
      fillet: .5
      points:
        - ref: mirror_matrix_index1_numerics
          shift: [0.5U, 0.5U + 0.475]
        - ref: mirror_matrix_index1_numerics
          shift: [1.74U + 2, 0.5U + 0.475]
        - ref: mirror_matrix_index1_numerics
          shift: [1.74U + 2, -4.87U + 2]
        - ref: mirror_matrix_index1_numerics
          shift: [0.5U, -4.87U + 2]
      operation: add
  left:
    - what: outline
      name: _left_no_mcu
    - what: polygon
      fillet: .5
      points:
        - ref: matrix_index1_numerics
          shift: [0.5U, 0.5U + 0.475]
        - ref: matrix_index1_numerics
          shift: [1.74U + 2, 0.5U + 0.475]
        - ref: matrix_index1_numerics
          shift: [1.74U + 2, -4.87U + 2]
        - ref: matrix_index1_numerics
          shift: [0.5U, -4.87U + 2]
      operation: add
  left-plate:
    - what: outline
      name: _left_no_mcu
    - where: [/^matrix_*/gm, /^thumb_*/gm]
      what: rectangle
      size: [cx, cy]
      operation: subtract
  right-plate:
    - what: outline
      name: _right_no_mcu
    - where: /^mirror_*/gm
      what: rectangle
      size: [cx, cy]
      operation: subtract
  full:
    - what: outline
      name: left
    - what: outline
      name: right
  full-plates:
    - what: outline
      name: left-plate
    - what: outline
      name: right-plate
  full-with-keys:
    - what: outline
      name: left
    - what: outline
      name: right
    - where: true
      what: rectangle
      size: [cx, cy]
      operation: stack
pcbs:
  clackr-left:
    template: kicad8
    outlines:
      main.outline: left
    footprints:
      mxvia:
        what: via
        where: [/^matrix_*/gm, /^thumb_*/gm]
        adjust:
          shift: [-7.6, -1.6]
        params:
          net: "{{column_net}}"
      mx:
        what: ceoloide/switch_mx
        where: [/^matrix_*/gm, /^thumb_*/gm]
        params:
          include_keycap: true
          hotswap: true
          solder: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: [/^matrix_*/gm, /^thumb_*/gm]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.6, -1.6]
          rotate: 90
      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_index1_numerics
          shift: [22.5, -6.55]
        params:
          show_silk_labels_on_both_sides: false
      rotaryenc:
        what: ceoloide/rotary_encoder_ec11_ec12
        where:
          ref: matrix_index1_home
          shift: [22.5, 0]
  clackr-right:
    template: kicad8
    outlines:
      main.outline: right
    footprints:
      mxvia:
        what: via
        where: /^mirror_*/gm
        adjust:
          shift: [-7.6, -1.6]
        params:
          net: "{{column_net}}"
      mx:
        what: ceoloide/switch_mx
        where: /^mirror_*/gm
        params:
          include_keycap: true
          solder: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: /^mirror_*/gm
        params:
          from: "{{row_net}}"
          to: "{{colrow}}"
        adjust:
          shift: [7.6, -1.6]
          rotate: 90
      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          ref: mirror_matrix_index1_numerics
          shift: [22.5, -6.55]
        params:
          show_silk_labels_on_both_sides: false