# `U` is a predefined unit of measure that means 19.05mm, which is MX spacing
meta:
  engine: 4.1.0
units:
  mxX: u
  mxY: u
points:
  zones:
    matrix:
      columns:
        pinky0:
          key:
            column_net: P1 
        pinky1:
          key:
            column_net: P0
        ring:
          key:
            column_net: P2
            stagger: 0.66U
            bind: [0,0,23.82,0]
          rows.modifiers.skip: true
        middle:
          key:
            column_net: P3
            stagger: 0.25U
            bind: [0,0,20,0]
          rows.modifiers.skip: true
        index0:
          key:
            column_net: P4
            stagger: -0.25U
            bind: [0,0,22,0]
          rows.modifiers.skip: true
        index1:
          key:
            column_net: P5
            stagger: -0.15U
            bind: [0,0,22,0]
          rows.modifiers.skip: true
      rows:
        modifiers:
          row_net: P14
          padding: U
        bottom:
          row_net: P15
          padding: U
        home:
          row_net: P18
          padding: U
        top:
          row_net: P19
          padding: U
        numerics:
          row_net: P20
          padding: U
    thumb:
      anchor:
        ref: matrix_ring_bottom
        shift: [1U, -1.25U]
      columns:
        tucky:
          key:
            row_net: P16
            column_net: P1
        reachy:
          key:
            row_net: P16
            column_net: P0
            spread: U
            splay: -10
            origin: [-0.5U, -0.5U]
        extra-reachy:
          key:
            row_net: P16
            column_net: P2
            spread: U
            splay: -10
            origin: [-0.5U, -0.5U]
            bind: [0,0.73333,0,0]
        extra-extra-reachy:
          key:
            row_net: P16
            column_net: P3
            spread: U
            splay: -10
            origin: [-0.5U, -0.5U]
            bind: [0,0,0,0.73333]
    rotary_encoder:
      anchor:
        ref: matrix_index1_home
        shift: [22, 0]
      columns:
        encoder:
          key:
            row_net: P14
            column_net: P5
            spread: U
            bind: [0,0,0,5]
  mirror:
    ref: "thumb_extra-extra-reachy"
    distance: 4U
outlines:
  _left_no_mcu:
    - where: [/^matrix_*/gm, /^thumb_*/gm, /^rotary_encoder_*/gm]
      what: rectangle
      size: [cx + 3, cy + 3]
      bound: true
      fillet: .5
      operation: add
  _right_no_mcu:
    - where: /^mirror_*/gm
      what: rectangle
      size: [cx + 3, cy + 3]
      bound: true
      fillet: .5
      operation: add
  _keycap_outlines:
    - what: rectangle
      fillet: 2
      where: true
      size: [mxX, mxY]
  right:
    - what: outline
      name: _right_no_mcu
      operation: stack
    - what: polygon
      fillet: .5
      points:
        - ref: mirror_matrix_index1_numerics
          shift: [0.5U, 0.5U + 0.475]
        - ref: mirror_matrix_index1_numerics
          shift: [1.74U + 2, 0.5U + 0.475]
        - ref: mirror_matrix_index1_numerics
          shift: [1.74U + 2, -4.87U + 2]
        - ref: mirror_matrix_index1_numerics
          shift: [0.5U, -4.87U + 2]
      operation: add
    - where: ["mirror_matrix_index1_numerics", "mirror_matrix_middle_numerics", "mirror_matrix_pinky1_numerics",
        "mirror_matrix_index1_home", "mirror_matrix_middle_home", "mirror_matrix_pinky1_bottom",
      ]
      what: circle
      radius: 1.1
      operation: stack
      adjust:
        shift: [-0.5U, -0.5U]
    - where: [/^mirror_rotary_encoder_*/gm]
      what: circle
      radius: 1.1
      operation: stack
      adjust:
        shift: [0U, -1.5U]
  left:
    - what: outline
      name: _left_no_mcu
      operation: stack
    - what: polygon
      fillet: .5
      points:
        - ref: matrix_index1_numerics
          shift: [0.5U, 0.5U + 0.475]
        - ref: matrix_index1_numerics
          shift: [1.74U + 2, 0.5U + 0.475]
        - ref: matrix_index1_numerics
          shift: [1.74U + 2, -4.87U + 2]
        - ref: matrix_index1_numerics
          shift: [0.5U, -4.87U + 2]
      operation: add
    - where: ["matrix_index1_numerics", "matrix_middle_numerics", "matrix_pinky1_numerics",
        "matrix_index1_home", "matrix_middle_home", "matrix_pinky1_bottom",
      ]
      what: circle
      radius: 1.1
      operation: stack
      adjust:
        shift: [-0.5U, -0.5U]
    - where: [/^rotary_encoder_*/gm]
      what: circle
      radius: 1.1
      operation: stack
      adjust:
        shift: [0U, -1.5U]
  _left_scaled:
    - what: outline
      name: left
      scale: 1.1
  _right_scaled:
    - what: outline
      name: right
      scale: 1.1
  left-plate:
    - what: outline
      name: _left_no_mcu
      operation: stack
    - where: [/^matrix_*/gm, /^thumb_*/gm, /^rotary_encoder_*/gm]
      what: rectangle
      size: [cx - 4, cy - 4]
      operation: stack
    - where: ["matrix_index1_numerics", "matrix_middle_numerics", "matrix_pinky1_numerics",
        "matrix_index1_home", "matrix_middle_home", "matrix_pinky1_bottom",
      ]
      what: circle
      radius: 1.1
      operation: stack
      adjust:
        shift: [-0.5U, -0.5U]
  right-plate:
    - what: outline
      name: _right_no_mcu
      operation: stack
    - where: /^mirror_*/gm
      what: rectangle
      size: [cx - 4, cy - 4]
      operation: stack
    - where: ["mirror_matrix_index1_numerics", "mirror_matrix_middle_numerics", "mirror_matrix_pinky1_numerics",
        "mirror_matrix_index1_home", "mirror_matrix_middle_home", "mirror_matrix_pinky1_bottom",
      ]
      what: circle
      radius: 1.1
      operation: stack
      adjust:
        shift: [-0.5U, -0.5U]
  full:
    - what: outline
      name: left
    - what: outline
      name: right
  full-plates:
    - what: outline
      name: left-plate
    - what: outline
      name: right-plate
  full-with-keys:
    - what: outline
      name: left
    - what: outline
      name: right
    - where: true
      what: rectangle
      size: [cx - 4, cy - 4]
      operation: stack
pcbs:
  clackr-left:
    template: kicad8
    outlines:
      main.outline: left
    footprints:
      mounting_holes:
        what: ceoloide/mounting_hole_npth
        where: [
          "matrix_index1_numerics", "matrix_middle_numerics", "matrix_pinky1_numerics",
          "matrix_index1_home", "matrix_middle_home", "matrix_pinky1_bottom",
        ]
        adjust:
          shift: [-0.5U, -0.5U]
      mounting_holes_edge:
        what: ceoloide/mounting_hole_npth
        where: [/^rotary_encoder_*/gm]
        adjust:
          shift: [0U, -1.5U]
      mxvia:
        what: via
        where: [/^matrix_*/gm, /^thumb_*/gm, /^rotary_encoder_*/gm]
        adjust:
          shift: [-7.6, -1.6]
        params:
          net: "{{column_net}}"
      mx:
        what: ceoloide/switch_mx
        where: [/^matrix_*/gm, /^thumb_*/gm, /^rotary_encoder_*/gm]
        params:
          include_keycap: true
          hotswap: true
          solder: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: [/^matrix_*/gm, /^thumb_*/gm, /^rotary_encoder_*/gm]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [7.6, -1.6]
          rotate: 90
      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_index1_numerics
          shift: [22, -8]
        params:
          show_silk_labels_on_both_sides: false
          P6: "MOSI"
          P7: "SCK"
          P10: "CS"
          P8: "RE_A"
          P9: "RE_C"
      rotaryenc:
        what: ceoloide/rotary_encoder_ec11_ec12
        where:
          ref: matrix_index1_home
          shift: [22, 0]
        params:
          S1: "P5"
          S2: "encoder_default"
      batterysw:
        what: ceoloide/power_switch_smd_side
        where:
          ref: matrix_index1_top
          shift: [33.35, 10]
        params:
          side: B
      batterypl:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: matrix_index1_numerics
          shift: [22, 0]
        params:
          side: B
      resetsw:
        what: ceoloide/reset_switch_smd_side
        where:
          ref: matrix_index1_top
          shift: [33.35, 0]
          rotate: 270
        params:
          side: B
      display:
        what: ceoloide/display_nice_view
        where:
          ref: matrix_index1_numerics
          shift: [22, -10]
        params:
          MOSI: "CS"
          SCK: "GND"
          VCC: "VCC"
          GND: "SCK"
          CS: "MOSI"
  clackr-right:
    template: kicad8
    outlines:
      main.outline: right
    footprints:
      mounting_holes:
        what: ceoloide/mounting_hole_npth
        where: [
          "mirror_matrix_index1_numerics", "mirror_matrix_middle_numerics", "mirror_matrix_pinky1_numerics",
          "mirror_matrix_index1_home", "mirror_matrix_middle_home", "mirror_matrix_pinky1_bottom",
        ]
        adjust:
          shift: [-0.5U, -0.5U]
      mounting_holes_edge:
        what: ceoloide/mounting_hole_npth
        where: [/^mirror_rotary_encoder_*/gm]
        adjust:
          shift: [0U, -1.5U]
      mxvia:
        what: via
        where: /^mirror_*/gm
        adjust:
          shift: [-7.6, -1.6]
        params:
          net: "{{column_net}}"
      mx:
        what: ceoloide/switch_mx
        where: /^mirror_*/gm
        params:
          include_keycap: true
          hotswap: true
          solder: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: /^mirror_*/gm
        params:
          to: "{{row_net}}"
          from: "{{colrow}}"
        adjust:
          shift: [7.6, -1.6]
          rotate: 270
      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          ref: mirror_matrix_index1_numerics
          shift: [22, -8]
        params:
          show_silk_labels_on_both_sides: false
          P6: "MOSI"
          P7: "SCK"
          P10: "CS"
          P8: "RE_A"
          P9: "RE_C"
      rotaryenc:
        what: ceoloide/rotary_encoder_ec11_ec12
        where:
          ref: mirror_matrix_index1_home
          shift: [22, 0]
        params:
          S1: "mirror_encoder_default"
          S2: "P5"
      batterysw:
        what: ceoloide/power_switch_smd_side
        where:
          ref: mirror_matrix_index1_top
          shift: [33.35, 10]
          rotate: 180
        params:
          side: B
      batterypl:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: mirror_matrix_index1_numerics
          shift: [22, 0]
        params:
          side: B
      resetsw:
        what: ceoloide/reset_switch_smd_side
        where:
          ref: mirror_matrix_index1_top
          shift: [33.35, 0]
          rotate: 270
        params:
          side: B
      display:
        what: ceoloide/display_nice_view
        where:
          ref: mirror_matrix_index1_numerics
          shift: [22, -10]
        params:
          MOSI: "CS"
          SCK: "GND"
          VCC: "VCC"
          GND: "SCK"
          CS: "MOSI"
